#!/bin/sh
#
# $Id: rocks-condor,v 1.14 2012/11/27 00:48:55 phil Exp $
#
# chkconfig: 345 92 92
# description: Reconfigure rocks frontend to use a new network setup
#
# @Copyright@
# 
# 				Rocks(r)
# 		         www.rocksclusters.org
# 		         version 5.6 (Emerald Boa)
# 		         version 6.1 (Emerald Boa)
# 
# Copyright (c) 2000 - 2013 The Regents of the University of California.
# All rights reserved.	
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
# 
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright
# notice unmodified and in its entirety, this list of conditions and the
# following disclaimer in the documentation and/or other materials provided 
# with the distribution.
# 
# 3. All advertising and press materials, printed or electronic, mentioning
# features or use of this software must display the following acknowledgement: 
# 
# 	"This product includes software developed by the Rocks(r)
# 	Cluster Group at the San Diego Supercomputer Center at the
# 	University of California, San Diego and its contributors."
# 
# 4. Except as permitted for the purposes of acknowledgment in paragraph 3,
# neither the name or logo of this software nor the names of its
# authors may be used to endorse or promote products derived from this
# software without specific prior written permission.  The name of the
# software includes the following terms, and any derivatives thereof:
# "Rocks", "Rocks Clusters", and "Avalanche Installer".  For licensing of 
# the associated name, interested parties should contact Technology 
# Transfer & Intellectual Property Services, University of California, 
# San Diego, 9500 Gilman Drive, Mail Code 0910, La Jolla, CA 92093-0910, 
# Ph: (858) 534-5815, FAX: (858) 534-7345, E-MAIL:invent@ucsd.edu
# 
# THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS''
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# @Copyright@
#
#

. /etc/init.d/functions

logfile=/var/log/dynip.log
conf_file="/root/net_conf.conf"

function reconfigFE() {

	#
	# redirect stdout and stderr 
	#
	exec > $logfile 2>&1
	
	
	
	# dhcp mode
	if [ ! -f $conf_file ] && [ -f "/etc/rocks-dhcp" ]; then 
		# we need to generate all the input value from the dhcp issued IPs
		public_interface=`rocks list attr |grep Kickstart_PublicInterface | awk '{print $2}'`
		
		mac=`cat /sys/class/net/$public_interface/address`
		ip=`ifconfig $public_interface |grep "inet "| awk '{ sub(/addr:/, "", $2); print $2 }'`
		net_mask=`ifconfig $public_interface |grep "inet "| awk '{ sub(/Mask:/, "", $4); print $4 }'`
		fqdn=`hostname`
		gw=`ip r|awk '/default/ {print $3}'`
		dns=`awk ' /nameserver/ {print $2}' /etc/resolv.conf | grep -v 127.0.0.1`
		#TODO finsh to fetch the values from the system and write the 
		echo "public_ip=\"$ip\"" > $conf_file
		echo "netmask=\"$net_mask\"" >> $conf_file
		echo "gw=\"gw\"" >> $conf_file
		echo "dns=\"$dns\"" >> $conf_file
		echo "fqdn=\"$fqdn\"" >> $conf_file
		echo '#use these two entries to specify new mac addresses' >> $conf_file
		echo 'eth0_mac=""' >> $conf_file
		echo 'eth1_mac=""' >> $conf_file
	
	
	
	fi
	
	/etc/init.d/network stop
	
	/opt/rocks/bin/rocks reconfigure $conf_file && mv $conf_file $conf_file.old


}



case "$1" in
    start)
        #action $"Condor Post Installation" $PRECONFIG 2> /dev/null
        echo "Starting dynip...."
	reconfigFE
        RETVAL=$?
        ;;
    stop)
	echo "Stopping dynip..."
        RETVAL=0
        ;;
    restart)
	echo restart not implemented yet
        #$0 stop
        #$0 start
        RETVAL=$?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $RETVAL
